services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./configs/bazarr:/config
      - ./media/library/movies:/movies
      - ./media/library/series:/tvshows
    ports:
      - 6767:6767
    restart: unless-stopped
  
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest 
    container_name: homarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    volumes:
      - ./configs/homarr:/appdata
    ports:
      - 4000:7575
    restart: unless-stopped

  byparr:
    image: ghcr.io/thephaseless/byparr
    container_name: byparr
    ports:
      - 8191:8191
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./configs/jellyfin:/config
      - ./media/library:/media
    ports:
      - 8096:8096 # web interface
      - 8920:8920 # secure interface
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./configs/prowlarr:/config 
    ports:
      - 9696:9696
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - WEBUI_PORT=8081
    volumes:
      - ./configs/qbittorrent:/config
      - ./media/downloads:/downloads
    ports:
      - 8081:8081
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./configs/radarr:/config
      - ./media/library/movies:/movies
      - ./media/downloads/movies:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr-series:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-series
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./configs/sonarr:/config
      - ./media/library/series:/tvshows
      - ./media/downloads/series:/downloads
    ports:
      - 8988:8989
    restart: unless-stopped
  
  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./configs/sonarr:/config
      - ./media/library/anime:/tvshows
      - ./media/downloads/anime:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./configs/readarr:/config
      - ./media/library/books:/books
      - ./media/downloads/books:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped

networks:
  default:
    name: media-server-network
