services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${HOME}/server/configs/bazarr:/config
      - ${HOME}/server/media/library/movies:/movies
      - ${HOME}/server/media/library/series:/tvshows
    ports:
      - 6767:6767
    restart: unless-stopped
  
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${HOME}/server/configs/dashy/conf.yaml:/app/user-data/conf.yaml   # Store Dashy config
    ports:
      - 4000:8080
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Rome
    volumes:
      - ${HOME}/server/configs/flaresolverr:/config   # Store FlareSolverr config
    ports:
      - 8191:8191
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${HOME}/server/configs/jellyfin:/config
      - ${HOME}/server/media/library:/media
    ports:
      - 8096:8096 # web interface
      - 8920:8920 # secure interface
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${HOME}/server/configs/prowlarr:/config 
    ports:
      - 9696:9696
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - WEBUI_PORT=8081
    volumes:
      - ${HOME}/server/configs/qbittorrent:/config
      - ${HOME}/server/media/downloads:/downloads
    ports:
    - 8801:8080
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${HOME}/server/configs/radarr:/config
      - ${HOME}/server/media/library/movies:/movies
      - ${HOME}/server/media/downloads/movies:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${HOME}/server/configs/sonarr:/config
      - ${HOME}/server/media/library/series:/tvshows
      - ${HOME}/server/media/downloads/series:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  
networks:
  default:
    name: media-server-network
