---
- Glances:
  - Glances:
    - abbr: GL
      href: https://status.home.pcb060.dev
      icon: glances

- Links:
    - Codeberg:
        - href: https://codeberg.org/pcb060/media-server.git
          description: This media server code repository
          icon: codeberg
    - Docs:
        - href: https://gethomepage.dev/configs/
          description: Documentation for homepage 
          icon: homepage
