---
title: pirateship
favicon: /images/gigiochad.png
headerStyle: boxed
useEqualHeights: true
target: _blank
quickLaunch:
  provider: custom
  url: https://kagi.com/search?q=
  target: _blank
  searchDescriptions: true
  mobileButtonPosition: bottom-right
disableIndexing: true # disables search engine indexing


layout:
  Library:
    tab: Media
    header: false
    style: row
    columns: 1
  Find:
    tab: Media
    style: row
    columns: 1

  Utils:
    tab: Utils
    header: false
    style: row
    columns: 1

  Nginx Proxy Manager:
    tab: Admin
    header: false
    style: row
    columns: 1
  Media Tools:
    tab: Admin
    style: row
    columns: 2
  Monitor:
    tab: Admin
    style: row
    columns: 2
  Glances:
    header: false
    tab: Admin
    style: row
    columns: 1
  Network:
    header: true
    tab: Admin
    style: row
    columns: 1
  Tailscale:
    icon: tailscale
    tab: Admin
    style: row
    columns: 2

  Links:
    style: row
    columns: 2
