---
title: pirateship
favicon: /images/gigiochad.png
headerStyle: boxed
useEqualHeights: true
target: _blank
quickLaunch:
  searchDescriptions: true
  mobileButtonPosition: bottom-right
disableIndexing: true # disables search engine indexing


layout:
  Enjoy:
    tab: General
    header: false
    style: row
    columns: 1
  Find:
    tab: General
    style: row
    columns: 2

  Admin:
    tab: Admin
    style: row
    columns: 3

  Monitor:
    tab: Monitor
    header: false
    style: row
    columns: 2 
  Glances:
    header: false
    tab: Monitor
    style: row
    columns: 1
  Tailscale: 
    icon: tailscale
    tab: Monitor
    style: row
    columns: 2 

  Links:
    style: row
    columns: 2

