---
- logo:
    icon: /images/gigiochad.png 

- openmeteo:
    label: Milano
    latitude: 45.4643
    longitude: 9.1895
    timezone: Europe/Rome
    units: metric
    cache: 10
    format:
      maximumFractionDigits: 1

- search:
    provider: duckduckgo
    target: _blank
