services:
  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    ports:
      - 8191:8191
    restart: unless-stopped

networks:
  media-server-network:
    external: true
