services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - TZ=Europe/Rome
      - PUID=1000
      - PGID=1000
      - TRUSTED_PROXY_COUNT=2
    env_file:
      - calibre-web-automated.env
    volumes:
      - ../configs/calibre-web-automated:/config
      - ../media/downloads/books:/cwa-book-ingest
      - ../media/library/books:/calibre-library
    ports:
      - 8083:8083
    restart: unless-stopped

networks:
  media-server-network:
    external: true