services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - TZ=Europe/Rome
      - HOMEPAGE_ALLOWED_HOSTS=home.pcb060.dev
    env_file:
      - homepage.env
    ports:
      - 3000:3000
    volumes:
      - ../configs/homepage:/app/config
      - ../resources/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

networks:
  media-server-network:
    external: true