services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v3.1.0
    container_name: immich-server
    env_file:
      - ./envs/immich.env
    environment:
      - TZ=Europe/Rome
    volumes:
      - ../media/library/photos:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - "group=library"
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v3.1.0
    env_file:
      - ./envs/immich.env
    volumes:
      - immich-model-cache:/cache
    restart: always
    labels:
      - "group=library"
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:8e8d64b405ce18f41b8e5ee20aa4687a8ed0022d1298f2ce31cdcf3a76e09411
    labels:
      - "group=library"
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    env_file:
      - ./envs/immich.env
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - ../configs/immich/pgdata:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    labels:
      - "group=library"
    healthcheck:
      disable: false

volumes:
  immich-model-cache:

networks:
  media-server-network:
    external: true
