services:
  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    ports:
      - 6868:6868
    volumes:
      - ../configs/profilarr:/config
    restart: unless-stopped

networks:
  media-server-network:
    external: true