services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ=Europe/Rome
      - PUID=1000
      - PGID=1000
    volumes:
      - ../configs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

networks:
  media-server-network:
    external: true